### ISSUE TITLE
Bug: 变量优先级的bug

### ISSUE THREAD

**Issue by Reimia** [WhiteMatrixTech/cd-template#1]
### Description

执行的命令

./cd-template --service=matrix-cloud-auth-service --config="./deploy-config.yml"

deploy-config.yml文件
```
app: matrix-cloud
# service name
service: matrix-cloud-example-service

# exposed port
ports:
  - port: 8080
    targetPort: 8080
    name: http

# enable metrics endpoint: default path is /metrics & default port is 5000
metrics:
  scrape: false
  path: /metrics/prometheus

# enable hpa
hpa: true
serviceAccountName: aws-access

```
生成的结果：

![image](https://user-images.githubusercontent.com/49182192/160317725-e3d22d38-3c44-42d2-8e75-76b4b56fe027.png)

**Minimal code-snippet showcasing the problem**
 

```ts

```

### Expected behavior

从命令行传入的 --service应当覆盖配置文件中的service
